# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-21 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
